name: .NET Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3 # Updated to the latest version

    - name: Setup .NET
      uses: actions/setup-dotnet@v2 # Updated to the latest version
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/Dino.csproj

    - name: Build
      run: dotnet build ./src/Dino.csproj --no-restore -c Release

    - name: Publish
      run: |
        dotnet publish ./src/Dino.csproj -c Release -r win-x64 \
        --self-contained true \
        /p:PublishTrimmed=true \
        /p:PublishSingleFile=true \
        /p:IncludeNativeLibrariesForSelfExtract=true \
        -o ./publish
      # Note: Adjust the publish options as needed for your project

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: ./publish/*
