name: .NET Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Adjust to match your project's target .NET version
        
    - name: Restore dependencies
      run: dotnet restore ./src/Dino.csproj
      
    - name: Build
      run: dotnet build ./src/Dino.csproj --no-restore -c Release
      
    - name: Publish
      run: |
        dotnet publish ./src/Dino.csproj -c Release -r win-x64 \
        --self-contained true \
        /p:PublishTrimmed=true \
        /p:PublishReadyToRun=true \
        -o ./publish
      # Note: Adjust the publish options as needed for your project
      
    - name: Archive Publish Output
      uses: actions/upload-artifact@v2
      with:
        name: publish-output
        path: ./publish/
